## Weiterführende Links:

- Frage auf Quora: https://www.quora.com/In-a-neural-style-transfer-why-does-using-Gram-matrices-keep-the-style
- Paper "Demystifying Neural Style Transfer": https://arxiv.org/abs/1701.01036

In [1]:
import numpy as np

a = np.array([
    [0.1, 0.1, 0.1, 0.1],
    [0.1, 1, 1, 0.1],
    [0.1, 0.1, 0.1, 0.1],
    [0.1, 0.1, 0.1, 0.1]
])

print(a @ a.T)

[[0.04 0.22 0.04 0.04]
 [0.22 2.02 0.22 0.22]
 [0.04 0.22 0.04 0.04]
 [0.04 0.22 0.04 0.04]]


In [6]:
import numpy as np

a = np.array([
    [0.1, 0.1, 0.1, 0.1],
    [0.1, 0.1, 0.1, 0.1],
    [0.1, 1, 1, 0.1],
    [0.1, 0.1, 0.1, 0.1]
])

print(a @ a.T)

[[0.04 0.04 0.22 0.04]
 [0.04 0.04 0.22 0.04]
 [0.22 0.22 2.02 0.22]
 [0.04 0.04 0.22 0.04]]
