In [61]:
import numpy as np

In [62]:
# Formel: Theta = (XT*X)^-1 * XT * y

X = np.array([
    [1, 10, 150],
    [1, 15, 120],
    [1, 10, 100]    
])
print(f"X {X}")

y = np.array([
    [300],
    [200],
    [250]
])
print(f"y {y}")

X [[  1  10 150]
 [  1  15 120]
 [  1  10 100]]
y [[300]
 [200]
 [250]]


In [63]:
Xt = np.transpose(X)
print(f"Xt {Xt}")
Xinv = np.linalg.inv(X)
print(f"Xinv: {Xinv}")

Xt [[  1   1   1]
 [ 10  15  10]
 [150 120 100]]
Xinv: [[-1.2  -2.    4.2 ]
 [-0.08  0.2  -0.12]
 [ 0.02 -0.   -0.02]]


In [64]:
# Formel: Theta = (XT*X)^-1 * XT * y
theta = np.matmul(np.matmul(np.linalg.inv(np.matmul(Xt, X)), Xt), y)
theta

array([[290.],
       [-14.],
       [  1.]])

In [65]:
X_test = [
    [1, 12, 120]
]

In [66]:
print(np.matmul(X_test, theta))

[[242.]]


In [67]:
from sklearn.linear_model import LinearRegression

In [68]:
model = LinearRegression(fit_intercept = True)
model.fit(X, y)
model.coef_

array([[  0., -14.,   1.]])

In [69]:
model.predict(X_test)

array([[242.]])