In [76]:
%matplotlib
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import binom

w = np.array([1, 2, 3, 4, 5, 6])
k = np.array([0, 1, 2, 3, 4, 5, 6])
print(w)
print(k)


Using matplotlib backend: Qt5Agg
[1 2 3 4 5 6]
[0 1 2 3 4 5 6]


In [77]:
for w_iter in w:
    fk_binom = binom.pmf(k, w_iter, 0.5)
    print(fk_binom)

[0.5 0.5 0.  0.  0.  0.  0. ]
[0.25 0.5  0.25 0.   0.   0.   0.  ]
[0.125 0.375 0.375 0.125 0.    0.    0.   ]
[0.0625 0.25   0.375  0.25   0.0625 0.     0.    ]
[0.03125 0.15625 0.3125  0.3125  0.15625 0.03125 0.     ]
[0.015625 0.09375  0.234375 0.3125   0.234375 0.09375  0.015625]


[0.16666667 0.         0.         0.         0.         0.        ]


ValueError: operands could not be broadcast together with shapes (7,) (6,) 

In [61]:
print(scipy.special.factorial(w))
y = 6 * scipy.special.factorial(w) / (np.math.factorial(w - k) * np.math.factorial(k)) * 0.5**k + 0.5**(w-k)

[  1.   2.   6.  24. 120. 720.]


ValueError: operands could not be broadcast together with shapes (6,) (100,) 